/* 2020-10-21 ∆¿Ω«Ω¿ 
1. SYS___ 
   SELECT * FROM DBA_USERS;
   DROP USER [USER_NAME] CASCADE;
2. SYS___
   DBA_TEAM ª˝º∫ π◊ ±««— ∫Œø©
3. DBA____
   STORE, GOODS, CUSTOMER, EMPLOYEE, STOCK ≈◊¿Ã∫Ì ª˝º∫ »ƒ 
     PROPERTY, CONSTRIANT, PUBLIC SYNONYM ª˝º∫
4. DBA_____
   DEV_TEAM ∞Ë¡§ ª˝º∫ »ƒ ≈◊¿Ã∫Ì ¡¢±Ÿ(SELECT) ±««— ∫Œø©
   DEV1_TEAM :: STORE, EMPLOYEE :: INSERT, UPDATE 
   DEV2_TEAM :: GOODS, STOCK :: INSERT, UPDATE 
   DEV3_TEAM ::  
   DEV4_TEAM :: CUSTOMER :: INSERT, UPDATE

5. CHECK

-- USER CHECK :: DBA
SELECT * FROM DBA_USERS;

-- TABLE CHECK :: DBA
SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLS WHERE TABLE_NAME = '';
SELECT * FROM USER_CONSTRAINT WHERE TABLE_NAME = '';

-- PRIVILEGES :: DBA
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE = 'HOON';
SELECT * FROM USER_TAB_PRIVS_MADE WHERE GRANTEE = 'HOON';

-- PRIVILEGES :: DEV
SELECT * FROM USER_TAB_PRIVS_RECD;

*/

/* DDL : DATA DEFINITION LANGUAGE
         : CREATE, ALTER, DROP
   DCL : DATA CONTROL LANGUAGE
         : GRANT, REVOKE 
   DML : DATA MANIPULATION LANGUAGE
         : INSERT, UPDATE, DELETE
 (S)QL : QUERY LANGUAGE
         : SELECT 
*/
/* INSERT INTO ~
    SYN_____
    INSERT INTO [TAB_NAME]([COL1_NAME], ..., [COLn_NAME]) 
    VALUES(VALUE1, ..., VALUEn);
    
    IMPORTANCE 
      :: RELATION¿Ã º≥¡§µ«æÓ ¿÷¥Ÿ∏È PARENT TABLE∫Œ≈Õ CHILD TABLE º¯º≠∑Œ INSERT ºˆ«‡
*/
--SYSDBA
CREATE USER SAM
IDENTIFIED BY "0000";

GRANT DBA TO SAM;

--TEAM_SAM
CREATE TABLE STORES(
 ST_CODE    NCHAR(4),
 ST_NAME    NVARCHAR2(100),
 ST_ADDR    NVARCHAR2(100)
)TABLESPACE USERS;

 ALTER TABLE STORES
 MODIFY ST_NAME NOT NULL;
 
 ALTER TABLE STORES
ADD CONSTRAINT ST_CODE_PK  PRIMARY KEY(ST_CODE);

CREATE PUBLIC SYNONYM ST FOR SAM.STORES;

CREATE TABLE GOODS(
 GO_CODE        NCHAR(4),
 GO_NAME        NVARCHAR2(50),
 GO_PRICE       NUMBER(7,0),
 GO_COMMENTS    NVARCHAR2(100)
)TABLESPACE USERS;

 ALTER TABLE GOODS
 MODIFY GO_NAME NOT NULL
 MODIFY GO_PRICE DEFAULT 0;
 
 ALTER TABLE GOODS
 ADD CONSTRAINT GO_CODE_PK   PRIMARY KEY(GO_CODE);

CREATE PUBLIC SYNONYM GO FOR SAM.GOODS;

CREATE TABLE CUSTOMER(
 CM_CODE    NCHAR(5),
 CM_NAME    NVARCHAR2(5),
 CM_PHONE   NCHAR(11)
)TABLESPACE USERS;

ALTER TABLE CUSTOMER
 ADD CONSTRAINT CM_CODE_PK  PRIMARY KEY(CM_CODE)
 ADD CONSTRAINT CM_PHONE_UQ UNIQUE(CM_PHONE);
 
 CREATE PUBLIC SYNONYM CM FOR SAM.CUSTOMER;
 CREATE TABLE EMPLOYEES(
 EM_STCODE      NCHAR(4),
 EM_CODE        NCHAR(4),
 EM_PWD         NVARCHAR2(10),
 EM_NAME        NVARCHAR2(5)
)TABLESPACE USERS;

ALTER TABLE EMPLOYEES 
ADD EM_LEVEL NCHAR(1);

ALTER TABLE EMPLOYEES 
MODIFY EM_LEVEL NOT NULL;

 ALTER TABLE EMPLOYEES
 MODIFY EM_PWD  NOT NULL
 MODIFY EM_NAME NOT NULL;
 
 ALTER TABLE EMPLOYEES
 ADD CONSTRAINT EM_STCODE_CODE_PK PRIMARY KEY(EM_STCODE, EM_CODE)
 ADD CONSTRAINT EM_STCODE_FK    FOREIGN KEY(EM_STCODE) REFERENCES STORES(ST_CODE);
 
 CREATE PUBLIC SYNONYM "EM" FOR SAM.EMPLOYEES;
 
 CREATE TABLE STOCK(
 SC_GOCODE NCHAR(4),
 SC_CODE   DATE,
 SC_STOCKS NUMBER(3,0),
 SC_EXPIRE DATE
 )TABLESPACE USERS;
 
 ALTER TABLE STOCK 
 MODIFY SC_STOCKS DEFAULT 0
 MODIFY SC_EXPIRE NOT NULL;
 
 ALTER TABLE STOCK
 ADD CONSTRAINT SC_GOCODE_CODE_PK PRIMARY KEY(SC_GOCODE, SC_CODE)
 ADD CONSTRAINT SC_GOCODE_FK FOREIGN KEY(SC_GOCODE) REFERENCES GOODS(GO_CODE);
 
 CREATE PUBLIC SYNONYM SC FOR SAM.STOCK;
 
 CREATE TABLE ORDERS(
 OD_CODE DATE,
 OD_EMSTCODE NCHAR(4),
 OD_EMCODE NCHAR(4),
 OD_CMCODE NCHAR(5),
 OD_STATE NCHAR(1)
 )TABLESPACE USERS;

 ALTER TABLE ORDERS
 MODIFY OD_EMSTCODE NOT NULL
 MODIFY OD_EMCODE NOT NULL
 MODIFY OD_CMCODE NOT NULL
 MODIFY OD_STATE NOT NULL;
 
 ALTER TABLE ORDERS
 ADD CONSTRAINT OD_CODE_PK PRIMARY KEY(OD_CODE)
 ADD CONSTRAINT OD_EMSTCODE_EMCODE_FK FOREIGN KEY(OD_EMSTCODE, OD_EMCODE) REFERENCES EMPLOYEES(EM_STCODE, EM_CODE)
 ADD CONSTRAINT OD_CMCODE_FK FOREIGN KEY(OD_CMCODE) REFERENCES CUSTOMER(CM_CODE);

CREATE PUBLIC SYNONYM OD FOR SAM.ORDERS;

CREATE TABLE ORDERDETAIL(
OT_ODCODE DATE,
OT_GOCODE NCHAR(4),
OT_QTY NUMBER(2,0),
OT_STATE NCHAR(1)
)TABLESPACE USERS;

ALTER TABLE ORDERDETAIL
 MODIFY OT_QTY DEFAULT 0
 MODIFY OT_STATE NOT NULL;
 
 ALTER TABLE ORDERDETAIL
 ADD CONSTRAINT OT_ODCODE_GOCODE_PK PRIMARY KEY(OT_ODCODE, OT_GOCODE)
 ADD CONSTRAINT OT_ODCODE_FK FOREIGN KEY(OT_ODCODE) REFERENCES ORDERS(OD_CODE)
 ADD CONSTRAINT OT_GOCODE_FK FOREIGN KEY(OT_GOCODE) REFERENCES GOODS(GO_CODE);
 
 CREATE PUBLIC SYNONYM OT FOR SAM.ORDERDETAIL;
 
 CREATE TABLE POINTS(
 PO_CMCODE NCHAR(5),
 PO_ODCODE DATE,
 PO_STATE NUMBER(1),
 PO_AMOUNT NUMBER(6,0)
 )TABLESPACE USERS;
 
 ALTER TABLE POINTS
 MODIFY PO_STATE NOT NULL
 MODIFY PO_AMOUNT DEFAULT 0;
 
 ALTER TABLE POINTS
 ADD CONSTRAINT PO_CMCODE_ODCODE_PK PRIMARY KEY(PO_CMCODE, PO_ODCODE)
 ADD CONSTRAINT PO_CMCODE_FK FOREIGN KEY(PO_CMCODE) REFERENCES CUSTOMER(CM_CODE)
 ADD CONSTRAINT PO_ODCODE_FK FOREIGN KEY(PO_ODCODE) REFERENCES ORDERS(OD_CODE);
 
 CREATE PUBLIC SYNONYM PO FOR SAM.POINTS;

 SELECT * FROM USER_TABLES;
 SELECT * FROM USER_TAB_COLS WHERE TABLE_NAME = 'STOCK';
 SELECT * FROM ALL_SYNONYMS WHERE TABLE_NAME = 'STOCK';
 SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME ='STOCK';
 
 CREATE USER FANA 
 IDENTIFIED BY "0000";
 
 CREATE USER NITO
 IDENTIFIED BY "0000";
 
 CREATE USER SON
 IDENTIFIED BY "0000";
 
 CREATE USER IU
 IDENTIFIED BY "0000";
 
 GRANT SELECT, INSERT, UPDATE ON SAM.STORES TO FANA;
 GRANT SELECT ON SAM.GOODS TO FANA;
 GRANT SELECT ON SAM.CUSTOMER TO FANA;
 GRANT SELECT, INSERT, UPDATE ON SAM.EMPLOYEES TO FANA;
 GRANT SELECT ON SAM.STOCK TO FANA;
 GRANT SELECT ON SAM.ORDERS TO FANA;
 GRANT SELECT ON SAM.POINTS TO FANA;
 GRANT SELECT ON SAM.ORDERDETAIL TO FANA;
 GRANT CONNECT, RESOURCE TO FANA;
 GRANT ALTER ON SAM.STORES TO FANA;
 GRANT ALTER ON SAM.EMPLOYEES TO FANA; 

 GRANT SELECT ON SAM.STORES TO NITO;
 GRANT SELECT, INSERT, UPDATE ON SAM.GOODS TO NITO;
 GRANT SELECT ON SAM.CUSTOMER TO NITO;
 GRANT SELECT ON SAM.EMPLOYEES TO NITO;
 GRANT SELECT, INSERT, UPDATE ON SAM.STOCK TO NITO; 
 GRANT SELECT ON SAM.ORDERS TO NITO;
 GRANT SELECT ON SAM.POINTS TO NITO;
 GRANT SELECT ON SAM.ORDERDETAIL TO NITO;
 GRANT CONNECT, RESOURCE TO NITO;
 GRANT ALTER ON SAM.GOODS TO NITO;
 GRANT ALTER ON SAM.STOCK TO NITO;
 
 GRANT SELECT ON SAM.STORES TO SON;
 GRANT SELECT ON SAM.GOODS TO SON;
 GRANT SELECT ON SAM.CUSTOMER TO SON;
 GRANT SELECT ON SAM.EMPLOYEES TO SON;
 GRANT SELECT ON SAM.STOCK TO SON;
 GRANT SELECT, INSERT, UPDATE ON SAM.ORDERS TO SON;
 GRANT SELECT ON SAM.POINTS TO SON;
 GRANT SELECT, INSERT, UPDATE ON SAM.ORDERDETAIL TO SON;
 GRANT CONNECT, RESOURCE TO SON;
 GRANT ALTER ON SAM.ORDERS TO SON;
 GRANT ALTER ON SAM.ORDERDETAIL TO SON;
 
 GRANT SELECT ON SAM.STORES TO IU;
 GRANT SELECT ON SAM.GOODS TO IU;
 GRANT SELECT,INSERT, UPDATE ON SAM.CUSTOMER TO IU;
 GRANT SELECT ON SAM.EMPLOYEES TO IU;
 GRANT SELECT ON SAM.STOCK TO IU;
 GRANT SELECT ON SAM.ORDERS TO IU;
 GRANT SELECT, INSERT, UPDATE ON SAM.POINTS TO IU;
 GRANT SELECT ON SAM.ORDERDETAIL TO IU;
 GRANT CONNECT, RESOURCE TO IU;
 GRANT ALTER ON SAM.CUSTOMER TO IU;
 GRANT ALTER ON SAM.POINTS TO IU;
 
SELECT * FROM USER_TAB_PRIVS_RECD;

--TEAM_SAM_FANA
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S001', 'SAM_MART_J', '¿ÕªÍΩ√ øµµÓµø');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S002', 'SAM_MART_H', '¿Œ√µ±§ø™Ω√ ∫Œ∆Ú±∏');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S003', 'SAM_MART_Y', '¿Œ√µ±§ø™Ω√ πÃ√ﬂ»¶±∏');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S004', 'SAM_MART_M', '¿Œ√µ±§ø™Ω√ ≥≤µø±∏');

INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E101', '1111', '±Ë¡æø¯', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E102', '1111', '«œ«ˆºˆ', 'A' );
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E103', '1111', '¿ØøµπŒ', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E104', '1111', '±ËπŒ±‚', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E201', '2222', '±Ë¡æø¯', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E202', '2222', '«œ«ˆºˆ', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E203', '2222', '¿ØøµπŒ', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E204', '2222', '±ËπŒ±‚', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E301', '3333', '±Ë¡æø¯', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E302', '3333', '«œ«ˆºˆ', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E303', '3333', '¿ØøµπŒ', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E304', '3333', '±ËπŒ±‚', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E401', '4444', '±Ë¡æø¯', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E402', '4444', '«œ«ˆºˆ', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E403', '4444', '¿ØøµπŒ', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E404', '4444', '±ËπŒ±‚', 'M');

SELECT * FROM ST;
SELECT * FROM "EM";

--TEAM_SAM_NITO
ALTER TABLE SAM.STOCK
MODIFY SC_CODE DEFAULT SYSDATE;

INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G001', '∞Ì√ﬂπŸªÁªË', 1150, 'π∫∞° πŸªÁªË «ÿ¡ˆ¥¬ ∏¿');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G002', 'ª—º≈ª—º≈ ƒƒ«ª≈Õ∏¿', 38500, NULL );
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G003', 'µ»¿Â∏¿ √Ú∆ƒÆèΩ∫', 5000, '±Ÿµ• ªˆ¿∫ ∞Ì√ﬂ¿Âªˆ');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G004', 'º¯«—∏¿ «œ«ˆºˆ', 999999, '¡®∆≤πˆ¿¸');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G005', '¥Î∏”∏ÆøÎ ∞°πﬂ', 3200, '∏”∏”∏Æ§ª_§ª');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G006', 'æÛ≈´ ∞®¿⁄≈¡', 300, '∞®¿⁄≈¡∏‘∞ÌΩÕ¥Ÿ');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G007', '»∆¬Ø¿« ø£≈Õ≈∞', 500000, 'ø£≈Õªß');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G008', '∂ﬂ∞≈øÓ æ∆¿ÃΩ∫æ∆∏ﬁ∏Æƒ´≥Î', 1150, '§ª§±§ª');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G009', 'ø©∏ßøÎ ƒ∆–µ˘', 110, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G010', 'π∞≈Î', 1250, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G011', 'BLAH BLAH', 1150, NULL);

INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G001', DEFAULT, 134, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G002', DEFAULT, 111, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G003', DEFAULT, 150, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G004', DEFAULT, 1, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G005', DEFAULT, 115, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G006', DEFAULT, 10, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G007', DEFAULT, 999, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G008', DEFAULT, 110, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G009', DEFAULT, 20, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G010', DEFAULT, 300, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G011', DEFAULT, 100, 20201231);

SELECT * FROM GO;
SELECT * FROM SC;

--TEAM_SAM_SON
ALTER TABLE SAM.ORDERS
MODIFY OD_CODE DEFAULT SYSDATE;

 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E101', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E101', 'CM003', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E102', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E101', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E201', 'CM005', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E301', 'CM006', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E403', 'CM005', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES (DEFAULT, 'S004', 'E402', 'CM004', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E302', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E201', 'CM003', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E402', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E203', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E104', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E404', 'CM007', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E202', 'CM008', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E401', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E104', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E404', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E302', 'CM006', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E301', 'CM005', 'P');

 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160929', 'YYYYMMDDHH24MISS'), 'G001', '9', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160929', 'YYYYMMDDHH24MISS'), 'G005', '20', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160929', 'YYYYMMDDHH24MISS'), 'G002', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160932', 'YYYYMMDDHH24MISS'), 'G003', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160932', 'YYYYMMDDHH24MISS'), 'G004', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160932', 'YYYYMMDDHH24MISS'), 'G001', '0', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160934', 'YYYYMMDDHH24MISS'), 'G017', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160934', 'YYYYMMDDHH24MISS'), 'G016', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160934', 'YYYYMMDDHH24MISS'), 'G015', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160935', 'YYYYMMDDHH24MISS'), 'G004', '6', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160935', 'YYYYMMDDHH24MISS'), 'G007', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160935', 'YYYYMMDDHH24MISS'), 'G003', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160937', 'YYYYMMDDHH24MISS'), 'G008', '10', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160937', 'YYYYMMDDHH24MISS'), 'G011', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160937', 'YYYYMMDDHH24MISS'), 'G012', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160939', 'YYYYMMDDHH24MISS'), 'G006', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160939', 'YYYYMMDDHH24MISS'), 'G005', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160939', 'YYYYMMDDHH24MISS'), 'G004', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160941', 'YYYYMMDDHH24MISS'), 'G003', '10', 'P'); 
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160941', 'YYYYMMDDHH24MISS'), 'G015', '7', 'P'); 
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160941', 'YYYYMMDDHH24MISS'), 'G014', '3', 'P'); 
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160943', 'YYYYMMDDHH24MISS'), 'G001', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160943', 'YYYYMMDDHH24MISS'), 'G008', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160943', 'YYYYMMDDHH24MISS'), 'G009', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160944', 'YYYYMMDDHH24MISS'), 'G005', '20', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160944', 'YYYYMMDDHH24MISS'), 'G013', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160944', 'YYYYMMDDHH24MISS'), 'G014', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160946', 'YYYYMMDDHH24MISS'), 'G007', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160946', 'YYYYMMDDHH24MISS'), 'G016', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160946', 'YYYYMMDDHH24MISS'), 'G013', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160948', 'YYYYMMDDHH24MISS'), 'G012', '10', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160948', 'YYYYMMDDHH24MISS'), 'G001', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160948', 'YYYYMMDDHH24MISS'), 'G002', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160950', 'YYYYMMDDHH24MISS'), 'G015', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160950', 'YYYYMMDDHH24MISS'), 'G014', '12', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160950', 'YYYYMMDDHH24MISS'), 'G017', '10', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160951', 'YYYYMMDDHH24MISS'), 'G012', '13', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160951', 'YYYYMMDDHH24MISS'), 'G005', '40', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160951', 'YYYYMMDDHH24MISS'), 'G003', '50', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160953', 'YYYYMMDDHH24MISS'), 'G006', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160953', 'YYYYMMDDHH24MISS'), 'G008', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160953', 'YYYYMMDDHH24MISS'), 'G003', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160955', 'YYYYMMDDHH24MISS'), 'G013', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160955', 'YYYYMMDDHH24MISS'), 'G014', '8', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160955', 'YYYYMMDDHH24MISS'), 'G006', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160956', 'YYYYMMDDHH24MISS'), 'G005', '11', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160956', 'YYYYMMDDHH24MISS'), 'G003', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160956', 'YYYYMMDDHH24MISS'), 'G007', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160958', 'YYYYMMDDHH24MISS'), 'G003', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160958', 'YYYYMMDDHH24MISS'), 'G007', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160958', 'YYYYMMDDHH24MISS'), 'G002', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160959', 'YYYYMMDDHH24MISS'), 'G005', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160959', 'YYYYMMDDHH24MISS'), 'G009', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160959', 'YYYYMMDDHH24MISS'), 'G016', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161001', 'YYYYMMDDHH24MISS'), 'G008', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161001', 'YYYYMMDDHH24MISS'), 'G003', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161001', 'YYYYMMDDHH24MISS'), 'G002', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161002', 'YYYYMMDDHH24MISS'), 'G017', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161002', 'YYYYMMDDHH24MISS'), 'G012', '8', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161002', 'YYYYMMDDHH24MISS'), 'G010', '4', 'P');
 
 SELECT * FROM OD;
 SELECT * FROM OT;
 
 --TEAM_SAM_IU
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM001','±Ë»∆','01010001000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM002','¿”»∆','01020002000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM003','≥≤»∆','01030003000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM004','¿Ã»∆','01040004000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM005','»∆»∆','01050005000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM006','√÷»∆','01060006000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM007','π⁄»∆','01070007000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM008','πÈ»∆','01080008000');

INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM001', TO_DATE('20201021160929','YYYYMMDDHH24MISS'), 1, '1000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM002', TO_DATE('20201021160932','YYYYMMDDHH24MISS'), -1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM003', TO_DATE('20201021160934','YYYYMMDDHH24MISS'), 1, '3000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20201021160935','YYYYMMDDHH24MISS'), -1, '4000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM005', TO_DATE('20201021160937','YYYYMMDDHH24MISS'), 1, '5000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM006', TO_DATE('20201021160939','YYYYMMDDHH24MISS'), -1, '6000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM007', TO_DATE('20201021160941','YYYYMMDDHH24MISS'), 1, '7000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM008', TO_DATE('20201021160943','YYYYMMDDHH24MISS'), -1, '8000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM001', TO_DATE('20201021160944','YYYYMMDDHH24MISS'), 1, '1000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM002', TO_DATE('20201021160946','YYYYMMDDHH24MISS'), -1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM003', TO_DATE('20201021160948','YYYYMMDDHH24MISS'), 1, '3000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20201021160950','YYYYMMDDHH24MISS'), -1, '4000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM005', TO_DATE('20201021160951','YYYYMMDDHH24MISS'), 1, '5000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM006', TO_DATE('20201021160953','YYYYMMDDHH24MISS'), -1, '6000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM007', TO_DATE('20201021160955','YYYYMMDDHH24MISS'), 1, '7000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM008', TO_DATE('20201021160956','YYYYMMDDHH24MISS'), -1, '8000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM001', TO_DATE('20201021160958','YYYYMMDDHH24MISS'), 1, '1000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM002', TO_DATE('20201021160959','YYYYMMDDHH24MISS'), -1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM003', TO_DATE('20201021161001','YYYYMMDDHH24MISS'), 1, '3000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20201021161002','YYYYMMDDHH24MISS'), -1, '4000');

SELECT * FROM CM;
SELECT * FROM PO;