/* 2020-10-21 ÆÀ½Ç½À 
1. SYS___ 
   SELECT * FROM DBA_USERS;
   DROP USER [USER_NAME] CASCADE;
2. SYS___
   DBA_TEAM »ý¼º ¹× ±ÇÇÑ ºÎ¿©
3. DBA____
   STORE, GOODS, CUSTOMER, EMPLOYEE, STOCK Å×ÀÌºí »ý¼º ÈÄ 
     PROPERTY, CONSTRIANT, PUBLIC SYNONYM »ý¼º
4. DBA_____
   DEV_TEAM °èÁ¤ »ý¼º ÈÄ Å×ÀÌºí Á¢±Ù(SELECT) ±ÇÇÑ ºÎ¿©
   DEV1_TEAM :: STORE, EMPLOYEE :: INSERT, UPDATE 
   DEV2_TEAM :: GOODS, STOCK :: INSERT, UPDATE 
   DEV3_TEAM ::  
   DEV4_TEAM :: CUSTOMER :: INSERT, UPDATE

5. CHECK

-- USER CHECK :: DBA
SELECT * FROM DBA_USERS;

-- TABLE CHECK :: DBA
SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLS WHERE TABLE_NAME = '';
SELECT * FROM USER_CONSTRAINT WHERE TABLE_NAME = '';

-- PRIVILEGES :: DBA
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE = 'HOON';
SELECT * FROM USER_TAB_PRIVS_MADE WHERE GRANTEE = 'HOON';

-- PRIVILEGES :: DEV
SELECT * FROM USER_TAB_PRIVS_RECD;

*/

/* DDL : DATA DEFINITION LANGUAGE
         : CREATE, ALTER, DROP
   DCL : DATA CONTROL LANGUAGE
         : GRANT, REVOKE 
   DML : DATA MANIPULATION LANGUAGE
         : INSERT, UPDATE, DELETE
 (S)QL : QUERY LANGUAGE
         : SELECT 
*/
/* INSERT INTO ~
    SYN_____
    INSERT INTO [TAB_NAME]([COL1_NAME], ..., [COLn_NAME]) 
    VALUES(VALUE1, ..., VALUEn);
    
    IMPORTANCE 
      :: RELATIONÀÌ ¼³Á¤µÇ¾î ÀÖ´Ù¸é PARENT TABLEºÎÅÍ CHILD TABLE ¼ø¼­·Î INSERT ¼öÇà
*/
--SYSDBA
CREATE USER SAM
IDENTIFIED BY "0000";

GRANT DBA TO SAM;

--TEAM_SAM
CREATE TABLE STORES(
 ST_CODE    NCHAR(4),
 ST_NAME    NVARCHAR2(100),
 ST_ADDR    NVARCHAR2(100)
)TABLESPACE USERS;

 ALTER TABLE STORES
 MODIFY ST_NAME NOT NULL;
 
 ALTER TABLE STORES
ADD CONSTRAINT ST_CODE_PK  PRIMARY KEY(ST_CODE);

CREATE PUBLIC SYNONYM ST FOR SAM.STORES;

CREATE TABLE GOODS(
 GO_CODE        NCHAR(4),
 GO_NAME        NVARCHAR2(50),
 GO_PRICE       NUMBER(7,0),
 GO_COMMENTS    NVARCHAR2(100)
)TABLESPACE USERS;

 ALTER TABLE GOODS
 MODIFY GO_NAME NOT NULL
 MODIFY GO_PRICE DEFAULT 0;
 
 ALTER TABLE GOODS
 ADD CONSTRAINT GO_CODE_PK   PRIMARY KEY(GO_CODE);

CREATE PUBLIC SYNONYM GO FOR SAM.GOODS;

CREATE TABLE CUSTOMER(
 CM_CODE    NCHAR(5),
 CM_NAME    NVARCHAR2(5),
 CM_PHONE   NCHAR(11)
)TABLESPACE USERS;

ALTER TABLE CUSTOMER
 ADD CONSTRAINT CM_CODE_PK  PRIMARY KEY(CM_CODE)
 ADD CONSTRAINT CM_PHONE_UQ UNIQUE(CM_PHONE);
 
 CREATE PUBLIC SYNONYM CM FOR SAM.CUSTOMER;
 CREATE TABLE EMPLOYEES(
 EM_STCODE      NCHAR(4),
 EM_CODE        NCHAR(4),
 EM_PWD         NVARCHAR2(10),
 EM_NAME        NVARCHAR2(5)
)TABLESPACE USERS;

ALTER TABLE EMPLOYEES 
ADD EM_LEVEL NCHAR(1);

ALTER TABLE EMPLOYEES 
MODIFY EM_LEVEL NOT NULL;

 ALTER TABLE EMPLOYEES
 MODIFY EM_PWD  NOT NULL
 MODIFY EM_NAME NOT NULL;
 
 ALTER TABLE EMPLOYEES
 ADD CONSTRAINT EM_STCODE_CODE_PK PRIMARY KEY(EM_STCODE, EM_CODE)
 ADD CONSTRAINT EM_STCODE_FK    FOREIGN KEY(EM_STCODE) REFERENCES STORES(ST_CODE);
 
 CREATE PUBLIC SYNONYM "EM" FOR SAM.EMPLOYEES;
 
 CREATE TABLE STOCK(
 SC_GOCODE NCHAR(4),
 SC_CODE   DATE,
 SC_STOCKS NUMBER(3,0),
 SC_EXPIRE DATE
 )TABLESPACE USERS;
 
 ALTER TABLE STOCK 
 MODIFY SC_STOCKS DEFAULT 0
 MODIFY SC_EXPIRE NOT NULL;
 
 ALTER TABLE STOCK
 ADD CONSTRAINT SC_GOCODE_CODE_PK PRIMARY KEY(SC_GOCODE, SC_CODE)
 ADD CONSTRAINT SC_GOCODE_FK FOREIGN KEY(SC_GOCODE) REFERENCES GOODS(GO_CODE);
 
 CREATE PUBLIC SYNONYM SC FOR SAM.STOCK;
 
 CREATE TABLE ORDERS(
 OD_CODE DATE,
 OD_EMSTCODE NCHAR(4),
 OD_EMCODE NCHAR(4),
 OD_CMCODE NCHAR(5),
 OD_STATE NCHAR(1)
 )TABLESPACE USERS;

 ALTER TABLE ORDERS
 MODIFY OD_EMSTCODE NOT NULL
 MODIFY OD_EMCODE NOT NULL
 MODIFY OD_CMCODE NOT NULL
 MODIFY OD_STATE NOT NULL;
 
 ALTER TABLE ORDERS
 ADD CONSTRAINT OD_CODE_PK PRIMARY KEY(OD_CODE)
 ADD CONSTRAINT OD_EMSTCODE_EMCODE_FK FOREIGN KEY(OD_EMSTCODE, OD_EMCODE) REFERENCES EMPLOYEES(EM_STCODE, EM_CODE)
 ADD CONSTRAINT OD_CMCODE_FK FOREIGN KEY(OD_CMCODE) REFERENCES CUSTOMER(CM_CODE);

CREATE PUBLIC SYNONYM OD FOR SAM.ORDERS;

CREATE TABLE ORDERDETAIL(
OT_ODCODE DATE,
OT_GOCODE NCHAR(4),
OT_QTY NUMBER(2,0),
OT_STATE NCHAR(1)
)TABLESPACE USERS;

ALTER TABLE ORDERDETAIL
 MODIFY OT_QTY DEFAULT 0
 MODIFY OT_STATE NOT NULL;
 
 ALTER TABLE ORDERDETAIL
 ADD CONSTRAINT OT_ODCODE_GOCODE_PK PRIMARY KEY(OT_ODCODE, OT_GOCODE)
 ADD CONSTRAINT OT_ODCODE_FK FOREIGN KEY(OT_ODCODE) REFERENCES ORDERS(OD_CODE)
 ADD CONSTRAINT OT_GOCODE_FK FOREIGN KEY(OT_GOCODE) REFERENCES GOODS(GO_CODE);
 
 CREATE PUBLIC SYNONYM OT FOR SAM.ORDERDETAIL;
 
 CREATE TABLE POINTS(
 PO_CMCODE NCHAR(5),
 PO_ODCODE DATE,
 PO_STATE NUMBER(1),
 PO_AMOUNT NUMBER(6,0)
 )TABLESPACE USERS;
 
 ALTER TABLE POINTS
 MODIFY PO_STATE NOT NULL
 MODIFY PO_AMOUNT DEFAULT 0;
 
 ALTER TABLE POINTS
 ADD CONSTRAINT PO_CMCODE_ODCODE_PK PRIMARY KEY(PO_CMCODE, PO_ODCODE)
 ADD CONSTRAINT PO_CMCODE_FK FOREIGN KEY(PO_CMCODE) REFERENCES CUSTOMER(CM_CODE)
 ADD CONSTRAINT PO_ODCODE_FK FOREIGN KEY(PO_ODCODE) REFERENCES ORDERS(OD_CODE);
 
 CREATE PUBLIC SYNONYM PO FOR SAM.POINTS;

 SELECT * FROM USER_TABLES;
 SELECT * FROM USER_TAB_COLS WHERE TABLE_NAME = 'STOCK';
 SELECT * FROM ALL_SYNONYMS WHERE TABLE_NAME = 'STOCK';
 SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME ='STOCK';
 
 CREATE USER FANA 
 IDENTIFIED BY "0000";
 
 CREATE USER NITO
 IDENTIFIED BY "0000";
 
 CREATE USER SON
 IDENTIFIED BY "0000";
 
 CREATE USER IU
 IDENTIFIED BY "0000";
 
 GRANT SELECT, INSERT, UPDATE ON SAM.STORES TO FANA;
 GRANT SELECT ON SAM.GOODS TO FANA;
 GRANT SELECT ON SAM.CUSTOMER TO FANA;
 GRANT SELECT, INSERT, UPDATE ON SAM.EMPLOYEES TO FANA;
 GRANT SELECT ON SAM.STOCK TO FANA;
 GRANT SELECT ON SAM.ORDERS TO FANA;
 GRANT SELECT ON SAM.POINTS TO FANA;
 GRANT SELECT ON SAM.ORDERDETAIL TO FANA;
 GRANT CONNECT, RESOURCE TO FANA;
 GRANT ALTER ON SAM.STORES TO FANA;
 GRANT ALTER ON SAM.EMPLOYEES TO FANA;
 GRANT CREATE VIEW TO FANA;

 GRANT SELECT ON SAM.STORES TO NITO;
 GRANT SELECT, INSERT, UPDATE ON SAM.GOODS TO NITO;
 GRANT SELECT ON SAM.CUSTOMER TO NITO;
 GRANT SELECT ON SAM.EMPLOYEES TO NITO;
 GRANT INSERT, UPDATE ON SAM.EMPLOYEES TO NITO;
 GRANT SELECT, INSERT, UPDATE ON SAM.STOCK TO NITO; 
 GRANT SELECT ON SAM.ORDERS TO NITO;
 GRANT SELECT ON SAM.POINTS TO NITO;
 GRANT SELECT ON SAM.ORDERDETAIL TO NITO;
 GRANT CONNECT, RESOURCE TO NITO;
 GRANT ALTER ON SAM.GOODS TO NITO;
 GRANT ALTER ON SAM.STOCK TO NITO;
 GRANT CREATE VIEW TO NITO;
 
 GRANT SELECT ON SAM.STORES TO SON;
 GRANT SELECT ON SAM.GOODS TO SON;
 GRANT SELECT ON SAM.CUSTOMER TO SON;
 GRANT SELECT ON SAM.EMPLOYEES TO SON;
 GRANT INSERT, UPDATE ON SAM.EMPLOYEES TO SON;
 GRANT SELECT ON SAM.STOCK TO SON;
 GRANT SELECT, INSERT, UPDATE ON SAM.ORDERS TO SON;
 GRANT SELECT ON SAM.POINTS TO SON;
 GRANT SELECT, INSERT, UPDATE ON SAM.ORDERDETAIL TO SON;
 GRANT CONNECT, RESOURCE TO SON;
 GRANT ALTER ON SAM.ORDERS TO SON;
 GRANT ALTER ON SAM.ORDERDETAIL TO SON;
 GRANT CREATE VIEW TO SON;
 
 GRANT SELECT ON SAM.STORES TO IU;
 GRANT SELECT ON SAM.GOODS TO IU;
 GRANT SELECT,INSERT, UPDATE ON SAM.CUSTOMER TO IU;
 GRANT SELECT ON SAM.EMPLOYEES TO IU;
 GRANT INSERT, UPDATE ON SAM.CUSTOMER TO IU;
 GRANT SELECT ON SAM.STOCK TO IU;
 GRANT SELECT ON SAM.ORDERS TO IU;
 GRANT SELECT, INSERT, UPDATE ON SAM.POINTS TO IU;
 GRANT SELECT ON SAM.ORDERDETAIL TO IU;
 GRANT CONNECT, RESOURCE TO IU;
 GRANT ALTER ON SAM.CUSTOMER TO IU;
 GRANT ALTER ON SAM.POINTS TO IU;
 GRANT CREATE VIEW TO IU;
 
 -----------------------------------------------
 /* 2020-10-27 */
 -----------------------------------------------
 CREATE TABLE HISTORY(
HI_EMCODE NCHAR(4),
HI_ACCESSDATE DATE,
HI_STATE NUMBER(1,0)
)TABLESPACE USERS;

ALTER TABLE HISTORY
ADD HI_EMSTCODE NCHAR(4);

ALTER TABLE HISTORY
MODIFY HI_STATE NOT NULL
MODIFY HI_ACCESSDATE DEFAULT SYSDATE;

ALTER TABLE HISTORY
ADD CONSTRAINT HI_EMSTCODE_EMCODE_ACDATE_PK PRIMARY KEY(HI_EMSTCODE, HI_EMCODE, HI_ACCESSDATE);

ALTER TABLE HISTORY
ADD CONSTRAINT HI_EMSTCODE_EMCODE_FK FOREIGN KEY(HI_EMSTCODE, HI_EMCODE) REFERENCES EMPLOYEES(EM_STCODE, EM_CODE);
  
CREATE PUBLIC SYNONYM HI FOR SAM.HISTORY;
  
GRANT SELECT, INSERT, UPDATE, ALTER ON SAM.HISTORY TO FANA;
GRANT SELECT ON SAM.HISTORY TO NITO;
GRANT INSERT ON SAM.HISTORY TO NITO;
GRANT SELECT ON SAM.HISTORY TO IU;
GRANT INSERT ON SAM.HISTORY TO IU;
GRANT SELECT ON SAM.HISTORY TO SON;
GRANT INSERT ON SAM.HISTORY TO SON;

SELECT * FROM USER_TAB_PRIVS_RECD;

/* 2020-10-22 SELECT 
    SYNTAXA__________
    5 * SELECT      [COL] AS "[ALIAS]", ..., [COL] AS "ALIAS"
    1 * FROM        [TAB | VIEW | INLINE-VIEW]
    2 * WHERE       [CONDITION]
    3   GROUP BY    [COL], ..., [COL]
    4   HAVING      [GROUP CONDITION]
    6   ORDER BY    [COL][ASC|DESC], ..., [COL][ASC|DESC]
*/
/* WHERE 
    COMPARATIVE OPERATOR :: > >= = !=(<>) < <= 
    COMBINED OPERATOR :: AND, OR
    ARITHMETIC OPERATOR :: + - * /
    SELECT OPERATOR :: IN(LIST), LIKE, IS NULL, NOT
*/
SELECT EM_STCODE AS "STCODE",
    EM_CODE AS "EMCODE",
    EM_NAME AS "EMNAME",
    EM_LEVEL AS "EMLEVEL"
FROM "EM"
WHERE EM_STCODE = 'S001' AND EM_CODE = 'E102';

SELECT GO_CODE AS "GOCODE",
    GO_NAME AS "GONAME",
    GO_PRICE AS "GOPRICE",
    GO_COMMENTS AS "GOCOMMENTS"
FROM GO;

SELECT GO_CODE AS "GOCODE",
    GO_NAME AS "GONAME",
    GO_PRICE AS "GOPRICE",
    GO_COMMENTS AS "GOCOMMENTS"
FROM GO
WHERE GO_CODE = 'G008' OR GO_CODE = 'G005' OR GO_CODE = 'G022';

-- IN
SELECT GO_CODE AS "GOCODE",
    GO_NAME AS "GONAME",
    GO_PRICE AS "GOPRICE",
    GO_COMMENTS AS "GOCOMMENTS"
FROM GO
WHERE GO_CODE IN(SELECT OT_GOCODE
                FROM OT);

/* LIKE
    WILD CARD :: % : ¸ðµç ¹®ÀÚ¸¦ ´ëÃ¼
              :: _ : ÇÏ³ªÀÇ ¹®ÀÚ¸¦ ´ëÃ¼
*/
SELECT *
FROM OT
WHERE OT_ODCODE LIKE '20201013' || '%';

SELECT *
FROM CM
WHERE CM_CODE LIKE '%' || '05' || '%' OR
      CM_NAME LIKE '%' || '05' || '%' OR
      CM_PHONE LIKE '%' || '05' || '%';

SELECT *
FROM (SELECT CM_CODE || CM_NAME || CM_PHONE AS FULLTEXT FROM CM)
WHERE FULLTEXT LIKE '%' || '05' || '%';

-- IS NULL
CREATE TABLE TESTS(
    T_CODE      NCHAR(1),
    T_PRICE     NUMBER(6,0),
    T_QTY       NUMBER(2,0)
)TABLESPACE USERS;

INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('1', 100, 1);
INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('2', 200, NULL);
INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('3', NULL, 10);
INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('4', 400, 10);
INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('5', NULL, NULL);
INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('6', 600, 5);
INSERT INTO TESTS(T_CODE, T_PRICE, T_QTY) VALUES('7', 700, 7);

SELECT * FROM TESTS;
-- ±Ý¾×(T_PRICE * T_QTY)ÀÌ 1000ÀÌ»óÀÎ ·¹ÄÚµå Ãâ·Â
SELECT *
FROM TESTS
WHERE (T_PRICE*T_QTY) >= 1000;

SELECT T_CODE, T_PRICE, T_QTY, COALESCE(T_PRICE*T_QTY, T_PRICE, T_QTY, 1)
FROM TESTS;

SELECT *
FROM TESTS
WHERE T_PRICE IS NOT NULL;


/* 2020-10-23 
    ORACLE FUNCTION
     - NUMERIC FUNCTIONS
       : ABS(n), CEIL(n), FLOOR(n), MOD(n), ROUND(n,m), TRUNC(n,m)
     - CHARACTER FUNCTIONS
       : CONCAT(C1, C2), INITCAP(C),  LOWER(C), UPPER(C), SUBSTR(C, m, n)
         LENGTH(C), REPLACE(C, c1, c2), INSTR(C, c, m, n)
     - DATETIME FUNCTIONS
       SYSDATE, SYSDATE +(-) NU, ADD_MONTH(D, NU), MONTHS_BETWEEN(D,D)
       LAST_DAY(D), NEXT_DAY(D, NU)
     - * CONVERSION FUNCTIONS
       : TO_CHAR(NU), TO_CHAR(NU, F), TO_CHAR(D, F), 
         TO_DATE(C, F), TO_NUMBER(C)
*/
SELECT ABS(65), ABS(-65)
FROM DUAL;

SELECT CEIL(1.956), FLOOR(1.956)
FROM DUAL;

SELECT 7/2, MOD(7, 2)
FROM DUAL;

SELECT ROUND(21.637, 0), ROUND(21.637, 1), ROUND(21.637, -1)
FROM DUAL;

SELECT ROUND(21.637, 0), TRUNC(21.637, 0)
FROM DUAL;

SELECT CONCAT(CONCAT('TEAM', 'SAM'), 'FANA'), 'TEAM' || 'SAM' || 'FANA'
FROM DUAL;

SELECT INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1),
    INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1, 2),
    INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1, 3),
    INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1, 4)
FROM DUAL;

SELECT TO_CHAR('1000000000000', 'L9,999,999,999,990'),
    TO_CHAR('0', 'L9,999,999,999,900'),
    TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    TO_DATE('201023095700', 'YYMMDDHH24MISS')
FROM DUAL;

SELECT SYSDATE AS "¿À´Ã",
    SYSDATE + 3 AS "3ÀÏ µÚ",
    ADD_MONTHS(SYSDATE, 3) AS "3°³¿ù µÚ",
    MONTHS_BETWEEN(SYSDATE, ADD_MONTHS(SYSDATE, 3)) AS "¿À´Ã - 3°³¿ù µÚ",
    MONTHS_BETWEEN(ADD_MONTHS(SYSDATE, 3), SYSDATE) AS "3°³¿ù µÚ - ¿À´Ã",
    LAST_DAY(ADD_MONTHS(SYSDATE, 3)) AS "3°³¿ù µÚ ¸¶Áö¸· ³¯",
    NEXT_DAY(ADD_MONTHS(SYSDATE, 3), 7) AS "3°³¿ù µÚ ÀÏ¿äÀÏ"
FROM DUAL;

/* JOIN 
    - µÎ °³ÀÇ Å×ÀÌºí¿¡ Á¸ÀçÇÏ´Â µ¥ÀÌÅÍ¸¦ ÇÏ³ªÀÇ Å×ÀÌºí·Î º¸¿©ÁÖ´Â ±â¼ú
    - VIEW¿Í ÇÔ²² È°¿ë
      -- µÎ °³ÀÇ Å×ÀÌºí¿¡ °øÅëµÈ ÄÃ·³(DATA-TYPE)ÀÌ Á¸Àç ÇØ¾ß »ç¿ë
      -- Å×ÀÌºí ALIAS¸¦ È°¿ëÇÏ¿© ½±°Ô Á¢±Ù °¡´É
    1. INNER JOIN
      -- °øÅëµÈ ÄÃ·³ÀÇ µ¥ÀÌÅÍ¸¦ ºñ±³ÇÏ¿© Á¤È®ÇÏ°Ô ÀÏÄ¡ÇÏ´Â ·¹ÄÚµå¸¸ ÃßÃâ
    2. OUTER JOIN
    
    SYNTAX______________
    SELECT [TAB ALIAS].[COL], ..., [TAB ALIAS].[COL]
    FROM [TAB] [ALIAS] INNER JOIN [TAB] [ALIAS] ON [JOIN-CONDITION]
    WHERE [TAB ALIAS].[COL] [COMPARE] [VALUE]
*/
-- JOINÀÇ È°¿ë
SELECT GO.GO_CODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    GO.GO_PRICE AS "GOPRICE",
    SC.SC_EXPIRE AS "SCEXPIRE"
FROM GO INNER JOIN SC ON GO.GO_CODE = SC.SC_GOCODE;

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R' AND OT.OT_ODCODE = '20201003113318';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R' AND OT.OT_GOCODE = 'G003';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R' AND (OT.OT_GOCODE = 'G003' OR OT.OT_GOCODE = 'G007');

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R' AND OT.OT_ODCODE = '20201003113318';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R' AND OT.OT_GOCODE = 'G003';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R' AND (OT.OT_GOCODE = 'G003' OR OT.OT_GOCODE = 'G007');

-- VIEWÀÇ È°¿ë
CREATE OR REPLACE VIEW ORDERINFO
AS
SELECT OT.OT_ODCODE AS "ODCODE",
    "EM".EM_STCODE AS "STCODE",
    ST.ST_NAME AS "STNAME",
    OD.OD_EMCODE AS "EMCODE",
    "EM".EM_NAME AS "EMNAME",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY * GO.GO_PRICE AS "PRICE",
    OT.OT_STATE AS "OTSTATE"
FROM OT INNER JOIN OD ON OT.OT_ODCODE = OD.OD_CODE
        INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
        INNER JOIN "EM" ON OD.OD_EMCODE = "EM".EM_CODE
        INNER JOIN ST ON "EM".EM_STCODE = ST.ST_CODE;

CREATE OR REPLACE VIEW EMPLOYEEINFO
AS
SELECT "EM".EM_STCODE AS "STCODE",
    ST.ST_NAME AS "STNAME",
    ST.ST_ADDR AS "STADDR",
    "EM".EM_CODE AS "EMCODE",
    "EM".EM_PWD AS "EMPWD",
    "EM".EM_NAME AS "EMNAME",
    "EM".EM_LEVEL AS "EMLEVEL"
FROM "EM" INNER JOIN ST ON "EM".EM_STCODE = ST.ST_CODE;

GRANT SELECT ON SAM.ORDERINFO TO FANA;
GRANT SELECT ON SAM.EMPLOYEEINFO TO FANA;

GRANT SELECT ON SAM.ORDERINFO TO NITO;
GRANT SELECT ON SAM.EMPLOYEEINFO TO NITO;

GRANT SELECT ON SAM.ORDERINFO TO SON;
GRANT SELECT ON SAM.EMPLOYEEINFO TO SON;

GRANT SELECT ON SAM.ORDERINFO TO IU;
GRANT SELECT ON SAM.EMPLOYEEINFO TO IU;


SELECT *
FROM SAM.ORDERINFO
WHERE OTSTATE != 'R' AND (GOCODE = 'G003' OR GOCODE = 'G007');

SELECT STNAME,
    EMNAME,
    EMLEVEL
FROM SAM.EMPLOYEEINFO
WHERE STCODE = 'S001';

SELECT STNAME,
    EMNAME,
    EMLEVEL
FROM SAM.EMPLOYEEINFO
WHERE EMCODE = 'E101';

SELECT STNAME,
    EMNAME,
    ODCODE,
    GONAME,
    OTQTY,
    GOPRICE,
    PRICE
FROM SAM.ORDERINFO
WHERE EMCODE = 'E101' AND ODCODE >= (ADD_MONTHS(SYSDATE, -1));

SELECT STNAME,
    EMNAME,
    ODCODE,
    GONAME,
    OTQTY,
    GOPRICE,
    PRICE
FROM SAM.ORDERINFO
WHERE EMCODE = 'E101' AND TO_CHAR(ODCODE, 'YYYYMMDD') >= TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYYMMDD');

SELECT ODCODE,
    GONAME,
    OTQTY,
    GOPRICE,
    PRICE
FROM SAM.ORDERINFO
WHERE GOCODE = 'G005' AND ODCODE >= (ADD_MONTHS(SYSDATE, -1));

SELECT ODCODE,
    GONAME,
    OTQTY,
    GOPRICE,
    PRICE
FROM SAM.ORDERINFO
WHERE GOCODE = 'G005' AND TO_CHAR(ODCODE, 'YYYYMMDD') >= TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYYMMDD');

/* 2020-10-26 */

/* Æ¯Á¤ »óÇ°ÀÇ ¿ùº° ¸ÅÃâ ÃßÀÌ 
    --------------------------------------
      ¸ÅÃâ¿ù        ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
    --------------------------------------
*/
CREATE OR REPLACE VIEW V1
AS
SELECT OD.OD_CMCODE AS "CMCODE",
        CM.CM_NAME AS "CMNAME",
        OD.OD_CODE AS "ODCODE"
FROM OD INNER JOIN CM ON OD.OD_CMCODE = CM.CM_CODE; 

GRANT SELECT ON SAM.V1 TO FANA;
GRANT SELECT ON SAM.V1 TO NITO;
GRANT SELECT ON SAM.V1 TO SON;
GRANT SELECT ON SAM.V1 TO IU;

CREATE OR REPLACE VIEW V2
AS
SELECT OD.OD_CODE AS "ODCODE",
        GO.GO_NAME AS "GONAME",
        SUM(OT.OT_QTY * GO.GO_PRICE) AS "PRICE"
FROM OT INNER JOIN OD ON OD.OD_CODE = OT.OT_ODCODE
        INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
GROUP BY OD.OD_CODE;

GRANT SELECT ON SAM.V2 TO FANA;
GRANT SELECT ON SAM.V2 TO NITO;
GRANT SELECT ON SAM.V2 TO SON;
GRANT SELECT ON SAM.V2 TO IU;

-- STEP 3 °í°´º° ÁÖ¹®°Ç¼ö, ÁÖ¹®ÃÑ±Ý¾× 
SELECT CMCODE,
        CMNAME,
        COUNT(V1.ODCODE),
        SUM(PRICE)
FROM SAM.V1 INNER JOIN SAM.V2 ON V1.ODCODE = V2.ODCODE
GROUP BY CMCODE, CMNAME;

/* JOIN°ú GROUP BY È°¿ë ¿¹Á¦ */
/* Æ¯Á¤ÀÏ(Æ¯Á¤¹üÀ§)ÀÇ »óÇ°º° ÆÇ¸Å ÇöÈ² 
    -- ÀÏÀÏ ¸ÅÃâÇöÈ²
    -- ¿ùº° ¸ÅÃâÇöÈ²
    ---------------------------------------------------
      »óÇ°ÄÚµå     »óÇ°¸í       ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
       OT GO        GO           OT        OT * GO
    ---------------------------------------------------
*/
CREATE OR REPLACE VIEW FV1
AS
SELECT OT.OT_GOCODE AS "GOCODE",
        GO.GO_NAME AS "GONAME",
        OT.OT_ODCODE AS "ODCODE",
        OT.OT_QTY AS "OTQTY",
        GO.GO_PRICE * OT.OT_QTY AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE;

-- Æ¯Á¤ÀÏÀÇ »óÇ°º° ¸ÅÃâÇöÈ²
SELECT GOCODE,
        GONAME,
        COUNT(ODCODE),
        SUM(PRICE)
FROM FV1
WHERE ODCODE LIKE '20201013' || '%'
GROUP BY GOCODE, GONAME;

-- Æ¯Á¤¹üÀ§ÀÇ »óÇ°º° ¸ÅÃâÇöÈ²
SELECT GOCODE,
        GONAME,
        COUNT(ODCODE),
        SUM(PRICE)
FROM FV1
WHERE TO_CHAR(ODCODE, 'YYYYMMDD') >= '20201013'  AND TO_CHAR(ODCODE, 'YYYYMMDD') <= '20201015'
GROUP BY GOCODE, GONAME;

/* Æ¯Á¤ »óÇ°ÀÇ ¿ùº° ¸ÅÃâ ÃßÀÌ 
    --------------------------------------
      ¸ÅÃâ¿ù        ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
    --------------------------------------
*/
SELECT TO_CHAR(OD_CODE, 'YYYYMM'),
        COUNT(OD_CODE)
FROM OD
GROUP BY TO_CHAR(OD_CODE, 'YYYYMM');

SELECT TO_CHAR(FV1.ODCODE, 'YYYYMM') AS "MONTHS",
        TEM.COUNT,
        SUM(PRICE)
FROM FV1 INNER JOIN (SELECT TO_CHAR(OD_CODE, 'YYYYMM') AS "ODCODE",
                           COUNT(OD_CODE) AS "COUNT"
                    FROM OD
                    GROUP BY TO_CHAR(OD_CODE, 'YYYYMM')) TEM ON TO_CHAR(FV1.ODCODE, 'YYYYMM') = TEM.ODCODE
GROUP BY TO_CHAR(FV1.ODCODE, 'YYYYMM'), TEM.COUNT;

/* Æ¯Á¤¿ùÀÇ º£½ºÆ® »óÇ°(ÆÇ¸Å°¹¼ö) ÇöÈ² 
    ------------------------------------------------------
      ¸ÅÃâ¿ù    »óÇ°ÄÚµå    »óÇ°¸í    ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
    ------------------------------------------------------
*/
CREATE OR REPLACE VIEW TEM1
AS
SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
        GOCODE,
        GONAME,
        COUNT(ODCODE) AS "COUNT",
        SUM(OTQTY) AS "QTY",
        SUM(PRICE) AS "PRICE"
FROM FV1
GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME;

SELECT MONTHS,
    MAX(QTY)
FROM TEM1
GROUP BY MONTHS;

SELECT *
FROM TEM1
WHERE (MONTHS, QTY) IN (SELECT MONTHS,
                                MAX(QTY)
                        FROM TEM1
                        GROUP BY MONTHS);
                        
/* JOIN°ú GROUP BY È°¿ë ¿¹Á¦ */
/* Æ¯Á¤ÀÏ(Æ¯Á¤¹üÀ§)ÀÇ »óÇ°º° ÆÇ¸Å ÇöÈ² 
    -- ÀÏÀÏ ¸ÅÃâÇöÈ²
    -- ¿ùº° ¸ÅÃâÇöÈ²
    ---------------------------------------------------
      »óÇ°ÄÚµå     »óÇ°¸í       ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
       OT GO        GO           OT        OT * GO
    ---------------------------------------------------
*/
CREATE OR REPLACE VIEW FV2
AS
SELECT OT.OT_GOCODE AS "GOCODE",
        GO.GO_NAME AS "GONAME",
        TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD') AS "ODCODE",
        COUNT(OT.OT_ODCODE) AS "COUNT",
        SUM(OT.OT_QTY) AS "OTQTY",
        SUM(GO.GO_PRICE * OT.OT_QTY) AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
GROUP BY TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD'), OT.OT_GOCODE, GO.GO_NAME;

CREATE OR REPLACE VIEW DAILYSALES
AS
SELECT OT.OT_GOCODE AS "GOCODE",
        GO.GO_NAME AS "GONAME",
        TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD') AS "ODCODE",
        GO.GO_PRICE AS "GOPRICE",
        OT.OT_QTY AS "OTQTY"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE;

-- Æ¯Á¤ÀÏÀÇ »óÇ°º° ¸ÅÃâÇöÈ²
SELECT GOCODE,
        GONAME,
        COUNT,
        PRICE
FROM FV2
WHERE ODCODE LIKE '20201013' || '%';

SELECT SUBSTR(ODCODE, 1 ,6),
        GOCODE,
        GONAME,
        GOPRICE,
        SUM(OTQTY) AS "OTQTY"
FROM DAILYSALES
WHERE ODCODE LIKE '202009' || '%'
GROUP BY SUBSTR(ODCODE, 1 ,6), GOCODE, GONAME, GOPRICE;


SELECT ODCODE,
        MAX(OTQTY)
FROM (SELECT SUBSTR(ODCODE, 1 ,6) AS "ODCODE",
                SUM(OTQTY) AS "OTQTY"
        FROM DAILYSALES
        WHERE ODCODE LIKE '202009' || '%'
        GROUP BY SUBSTR(ODCODE, 1 ,6), GOPRICE)
GROUP BY ODCODE;

SELECT GOCODE,
        GONAME,
        GOPRICE,
        OTQTY
FROM (SELECT SUBSTR(ODCODE, 1 ,6) AS "ODCODE",
            GOCODE AS "GOCODE",
            GONAME AS "GONAME",
            GOPRICE AS "GOPRICE",
            SUM(OTQTY) AS "OTQTY"
        FROM DAILYSALES
        WHERE ODCODE LIKE '202009' || '%'
        GROUP BY SUBSTR(ODCODE, 1 ,6), GOCODE, GONAME, GOPRICE)
WHERE (ODCODE, OTQTY) IN (SELECT ODCODE,
                                    MAX(OTQTY)
                            FROM (SELECT SUBSTR(ODCODE, 1 ,6) AS "ODCODE",
                                            SUM(OTQTY) AS "OTQTY"
                                    FROM DAILYSALES
                                    WHERE ODCODE LIKE '202009' || '%'
                                    GROUP BY SUBSTR(ODCODE, 1 ,6), GOPRICE)
                            GROUP BY ODCODE);

-- Æ¯Á¤¹üÀ§ÀÇ »óÇ°º° ¸ÅÃâÇöÈ²
SELECT GOCODE,
        GONAME,
        COUNT,
        PRICE
FROM FV2
WHERE ODCODE >= '20201013' AND ODCODE <= '20201015';

/* Æ¯Á¤ »óÇ°ÀÇ ¿ùº° ¸ÅÃâ ÃßÀÌ 
    --------------------------------------
      ¸ÅÃâ¿ù        ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
      OD/OT          OD         OT * GO
    --------------------------------------
*/
SELECT * FROM OD;

SELECT TO_CHAR(OD_CODE, 'YYYYMM'),
        COUNT(OD_CODE)
FROM OD
GROUP BY TO_CHAR(OD_CODE, 'YYYYMM');

SELECT SUBSTR(FV2.ODCODE, 1, 6) AS "MONTHS",
        TEM.COUNT,
        SUM(PRICE)
FROM FV2 INNER JOIN (SELECT TO_CHAR(OD_CODE, 'YYYYMM') AS "ODCODE",
                           COUNT(OD_CODE) AS "COUNT"
                    FROM OD
                    GROUP BY TO_CHAR(OD_CODE, 'YYYYMM')) TEM ON SUBSTR(FV2.ODCODE, 1, 6) = TEM.ODCODE
GROUP BY SUBSTR(FV2.ODCODE, 1, 6), TEM.COUNT;

/* Æ¯Á¤¿ùÀÇ º£½ºÆ® »óÇ°(ÆÇ¸Å°¹¼ö) ÇöÈ² 
    ------------------------------------------------------
      ¸ÅÃâ¿ù    »óÇ°ÄÚµå    »óÇ°¸í    ÁÖ¹®°Ç¼ö    ÆÇ¸Å°¹¼ö       ¸ÅÃâ¾×
      OD/OT     OT/GO       GO        OT        OT           OT*GO
FV2.ODCODE,FV2.GOCODE,FV2.GONAME,FV2.COUNT,FV2.OTQTY,FV2.PRICE
      FV2
    ------------------------------------------------------
*/
CREATE OR REPLACE VIEW TEM2
AS
SELECT SUBSTR(ODCODE, 1, 6) AS "MONTHS",
        GOCODE,
        GONAME,
        SUM(COUNT) AS "COUNT",
        SUM(OTQTY) AS "QTY",
        SUM(PRICE) AS "PRICE"
FROM FV2
GROUP BY SUBSTR(ODCODE, 1, 6), GOCODE, GONAME;

SELECT MONTHS,
        MAX(QTY)
FROM TEM2
GROUP BY MONTHS;

SELECT *
FROM TEM2
WHERE (MONTHS, QTY) IN(SELECT MONTHS,
                                MAX(QTY)
                        FROM TEM2
                        GROUP BY MONTHS);
                        
/*2020-10-27*/
/* ¿ùº° ¸ÅÃâ ÃßÀÌ 
    --------------------------------------
      ¸ÅÃâ¿ù        ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
    --------------------------------------
*/
/*
SELECT TO_CHAR(OD_CODE, 'YYYYMM'),
        COUNT(OD_CODE)
FROM OD
GROUP BY TO_CHAR(OD_CODE, 'YYYYMM');
*/
SELECT TO_CHAR(FV1.ODCODE, 'YYYYMM') AS "MONTHS",
        TEM.COUNT,
        SUM(PRICE)
FROM FV1 INNER JOIN (SELECT TO_CHAR(OD_CODE, 'YYYYMM') AS "ODCODE",
                           COUNT(OD_CODE) AS "COUNT"
                    FROM OD
                    GROUP BY TO_CHAR(OD_CODE, 'YYYYMM')) TEM ON TO_CHAR(FV1.ODCODE, 'YYYYMM') = TEM.ODCODE
GROUP BY TO_CHAR(FV1.ODCODE, 'YYYYMM'), TEM.COUNT;

/* Æ¯Á¤ »óÇ°ÀÇ ¿ùº° ¸ÅÃâ ÃßÀÌ 
    --------------------------------------
      ¸ÅÃâ¿ù        ÁÖ¹®°Ç¼ö       ¸ÅÃâ¾×
    --------------------------------------
*/
SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
        COUNT(ODCODE) AS "COUNT",
        SUM(PRICE) AS "PRICE"
FROM FV1
WHERE GOCODE = 'G005'
GROUP BY TO_CHAR(ODCODE, 'YYYYMM');

/* Æ¯Á¤¿ùÀÇ º£½ºÆ® »óÇ°(ÆÇ¸Å°¹¼ö) ÇöÈ² 
    ----------------------------------------------------------
      ¸ÅÃâ¿ù    »óÇ°ÄÚµå    »óÇ°¸í    ÁÖ¹®°Ç¼ö    ÆÇ¸Å°¹¼ö    ¸ÅÃâ¾×
    ----------------------------------------------------------
*/
/*
SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
        GOCODE AS "GOCODE",
        GONAME AS "GONAME",
        COUNT(ODCODE) AS "ODCOUNT",
        SUM(OTQTY) AS "OTQTY",
        SUM(PRICE) AS "PRICE"
FROM FV1
GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME;
*/
/*
SELECT TEM.MONTHS,
        MAX(TEM.OTQTY)
FROM (SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
            GOCODE AS "GOCODE",
            GONAME AS "GONAME",
            COUNT(ODCODE) AS "ODCOUNT",
            SUM(OTQTY) AS "OTQTY",
            SUM(PRICE) AS "PRICE"
    FROM FV1
    GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME)TEM
GROUP BY TEM.MONTHS;
*/
/*
SELECT *
FROM (SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
            GOCODE AS "GOCODE",
            GONAME AS "GONAME",
            SUM(OTQTY) AS "OTQTY",
            SUM(PRICE) AS "PRICE"
    FROM FV1
    GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME)TEM2
WHERE (TEM2.MONTHS, TEM2.OTQTY) IN(SELECT TEM1.MONTHS,
                                        MAX(TEM1.OTQTY)
                                FROM (SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
                                            GOCODE AS "GOCODE",
                                            GONAME AS "GONAME",
                                            SUM(OTQTY) AS "OTQTY",
                                            SUM(PRICE) AS "PRICE"
                                    FROM FV1
                                    GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME)TEM1
                                GROUP BY TEM1.MONTHS);
*/                                
SELECT *
FROM (SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
            GOCODE AS "GOCODE",
            GONAME AS "GONAME",
            SUM(OTQTY) AS "OTQTY",
            SUM(PRICE) AS "PRICE"
    FROM FV1
    GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME)TEM1
WHERE TEM1.MONTHS = '202009' AND
    (TEM1.MONTHS, TEM1.OTQTY) IN(SELECT TEM2.MONTHS,
                                        MAX(TEM2.OTQTY)
                                FROM (SELECT TO_CHAR(ODCODE, 'YYYYMM') AS "MONTHS",
                                            GOCODE AS "GOCODE",
                                            GONAME AS "GONAME",
                                            SUM(OTQTY) AS "OTQTY",
                                            SUM(PRICE) AS "PRICE"
                                    FROM FV1
                                    GROUP BY TO_CHAR(ODCODE, 'YYYYMM'), GOCODE, GONAME)TEM2
                                GROUP BY TEM2.MONTHS);
/* ½Ã°£´ëº° ¸ÅÃâÃßÀÌ 
    --------------------------------
      ½Ã°£     Æò±ÕÁÖ¹®°Ç¼ö  Æò±Õ¸ÅÃâ¾×
    --------------------------------
*/
/*
SELECT TO_CHAR(OD_CODE, 'YYYYMMDDHH24') AS "HOUR",
        COUNT(OD_CODE) AS "ODCOUNT"
FROM OD
GROUP BY TO_CHAR(OD_CODE, 'YYYYMMDDHH24');
*/
SELECT SUBSTR(TEM."HOUR", 9, 2) || '½Ã' AS "½Ã°£",
        ROUND(AVG(TEM.ODCOUNT), 1) AS "Æò±ÕÁÖ¹®°Ç¼ö",
        TO_CHAR(ROUND(AVG(FV1.PRICE), 1), '999,999.0') AS "Æò±Õ¸ÅÃâ¾×"
FROM FV1 INNER JOIN (SELECT TO_CHAR(OD_CODE, 'YYYYMMDDHH24') AS "HOUR",
                            COUNT(OD_CODE) AS "ODCOUNT"
                            FROM OD
                            GROUP BY TO_CHAR(OD_CODE, 'YYYYMMDDHH24'))TEM ON TO_CHAR(FV1.ODCODE, 'YYYYMMDDHH24') = TEM."HOUR"
GROUP BY SUBSTR(TEM."HOUR", 9, 2) || '½Ã';

/* ¿äÀÏº° ¸ÅÃâÃßÀÌ 
    --------------------------------
      ¿äÀÏ     Æò±ÕÁÖ¹®°Ç¼ö  Æò±Õ¸ÅÃâ¾×
    --------------------------------
*/
/*
SELECT TO_CHAR(OD_CODE, 'YYYYMMDD') AS "DATE",
        TO_CHAR(OD_CODE, 'DAY') AS "DAY",
        COUNT(OD_CODE) AS "ODCOUNT"
FROM OD
GROUP BY TO_CHAR(OD_CODE, 'YYYYMMDD'), TO_CHAR(OD_CODE, 'DAY');

SELECT TO_CHAR(ODCODE, 'YYYYMMDD') AS "DATE",
        TO_CHAR(ODCODE, 'DAY') AS "DAY",
        SUM(PRICE) AS "PRICE"
FROM FV1
GROUP BY TO_CHAR(ODCODE, 'YYYYMMDD'), TO_CHAR(ODCODE, 'DAY');
*/
SELECT TEM1."DAY" AS "¿äÀÏ",
        ROUND(AVG(TEM2.ODCOUNT),1) AS "Æò±ÕÁÖ¹®°Ç¼ö",
        TO_CHAR(ROUND(AVG(TEM1.PRICE),1), '999,999,999.0') AS "Æò±Õ¸ÅÃâ¾×"
FROM (SELECT TO_CHAR(ODCODE, 'YYYYMMDD') AS "DATE",
            TO_CHAR(ODCODE, 'DAY') AS "DAY",
            SUM(PRICE) AS "PRICE"
        FROM FV1
        GROUP BY TO_CHAR(ODCODE, 'YYYYMMDD'), TO_CHAR(ODCODE, 'DAY'))TEM1 INNER JOIN
    (SELECT TO_CHAR(OD_CODE, 'YYYYMMDD') AS "DATE",
            TO_CHAR(OD_CODE, 'DAY') AS "DAY",
            COUNT(OD_CODE) AS "ODCOUNT"
        FROM OD
        GROUP BY TO_CHAR(OD_CODE, 'YYYYMMDD'), TO_CHAR(OD_CODE, 'DAY'))TEM2 ON TEM1."DAY" = TEM2."DAY" AND TEM1."DATE" = TEM2."DATE"
GROUP BY TEM1."DAY";
/*
SELECT TO_CHAR(OD_CODE, 'YYYYMMDD') AS "DATE",
        TO_CHAR(OD_CODE, 'DAY') AS "DAY",
        COUNT(*) AS "ODCOUNT"
FROM OD
GROUP BY TO_CHAR(OD_CODE, 'YYYYMMDD'), TO_CHAR(OD_CODE, 'DAY');

SELECT TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD') AS "DATE",
        TO_CHAR(OT.OT_ODCODE, 'DAY') AS "DAY",
        SUM(OT.OT_QTY * GO.GO_PRICE) AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
GROUP BY TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD'), TO_CHAR(OT.OT_ODCODE, 'DAY');
*/
SELECT TEM1."DAY" AS "¿äÀÏ",
        ROUND(AVG(TEM1.ODCOUNT), 1) AS "Æò±ÕÁÖ¹®°Ç¼ö",
        TO_CHAR(ROUND(AVG(TEM2.PRICE), 1), '999,999,999.0') AS "Æò±Õ¸ÅÃâ¾×"
FROM (SELECT TO_CHAR(OD_CODE, 'YYYYMMDD') AS "DATE",
            TO_CHAR(OD_CODE, 'DAY') AS "DAY",
            COUNT(*) AS "ODCOUNT"
        FROM OD
        GROUP BY TO_CHAR(OD_CODE, 'YYYYMMDD'), TO_CHAR(OD_CODE, 'DAY')) TEM1
        INNER JOIN (SELECT TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD') AS "DATE",
                            TO_CHAR(OT.OT_ODCODE, 'DAY') AS "DAY",
                            SUM(OT.OT_QTY * GO.GO_PRICE) AS "PRICE"
                    FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
                    GROUP BY TO_CHAR(OT.OT_ODCODE, 'YYYYMMDD'), TO_CHAR(OT.OT_ODCODE, 'DAY')) TEM2 ON TEM1."DAY" = TEM2."DAY" AND TEM1."DATE" = TEM2."DATE"
GROUP BY TEM1."DAY";

--TEAM_SAM_FANA
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S001', 'SAM_MART_J', 'ÀÍ»ê½Ã ¿µµîµ¿');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S002', 'SAM_MART_H', 'ÀÎÃµ±¤¿ª½Ã ºÎÆò±¸');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S003', 'SAM_MART_Y', 'ÀÎÃµ±¤¿ª½Ã ¹ÌÃßÈ¦±¸');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S004', 'SAM_MART_M', 'ÀÎÃµ±¤¿ª½Ã ³²µ¿±¸');

INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E101', '1111', '±èÁ¾¿ø', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E102', '1111', 'ÇÏÇö¼ö', 'A' );
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E103', '1111', 'À¯¿µ¹Î', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E104', '1111', '±è¹Î±â', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E201', '2222', '±èÁ¾¿ø', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E202', '2222', 'ÇÏÇö¼ö', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E203', '2222', 'À¯¿µ¹Î', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E204', '2222', '±è¹Î±â', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E301', '3333', '±èÁ¾¿ø', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E302', '3333', 'ÇÏÇö¼ö', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E303', '3333', 'À¯¿µ¹Î', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E304', '3333', '±è¹Î±â', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E401', '4444', '±èÁ¾¿ø', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E402', '4444', 'ÇÏÇö¼ö', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E403', '4444', 'À¯¿µ¹Î', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E404', '4444', '±è¹Î±â', 'M');

ALTER TABLE SAM.HISTORY
MODIFY HI_STATE DEFAULT 0;

SELECT COUNT(*) AS "ISEMCODE"
FROM EM
WHERE EM_CODE = 'E101' AND EM_STCODE = 'S001';

SELECT COUNT(*)
FROM EM
WHERE EM_STCODE = 'S001' AND EM_CODE = 'E101' AND EM_PWD = '1111';

SELECT HI_EMSTCODE AS "STCODE",
        HI_EMCODE AS "EMCODE",
        SUM(HI_STATE) AS "STATE"
FROM HI
GROUP BY HI_EMSTCODE, HI_EMCODE;

INSERT INTO HI(HI_EMSTCODE, HI_EMCODE, HI_ACCESSDATE, HI_STATE)
VALUES('S001', 'E101', DEFAULT, 1);
INSERT INTO HI(HI_EMSTCODE, HI_EMCODE, HI_ACCESSDATE, HI_STATE)
VALUES('S001', 'E101', DEFAULT, -1);

SELECT ST.ST_NAME AS "STNAME",
        "EM".EM_NAME AS "EMNAME",
        "EM".EM_LEVEL AS "EMLEVEL",
        TO_CHAR(MAX(HI.HI_ACCESSDATE), 'YYYYMMDDHH24MISS') AS "HIACCESSDATE",
        HI.HI_EMSTCODE AS "STCODE",
        HI.HI_EMCODE AS "EMCODE"
FROM HI INNER JOIN "EM" ON HI.HI_EMCODE = "EM".EM_CODE AND HI.HI_EMSTCODE = "EM".EM_STCODE
        INNER JOIN ST ON HI.HI_EMSTCODE = ST.ST_CODE
WHERE HI.HI_STATE = 1
        AND HI.HI_EMSTCODE = 'S001'
        AND HI.HI_EMCODE = 'E101'
GROUP BY ST.ST_NAME, "EM".EM_NAME, "EM".EM_LEVEL, HI.HI_EMSTCODE, HI.HI_EMCODE;

SELECT * FROM ST;
SELECT * FROM "EM";
SELECT * FROM HI;

--TEAM_SAM_NITO
ALTER TABLE SAM.STOCK
MODIFY SC_CODE DEFAULT SYSDATE;

INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G001', '°íÃß¹Ù»ç»è', 1150, '¹º°¡ ¹Ù»ç»è ÇØÁö´Â ¸À');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G002', '»Ñ¼Å»Ñ¼Å ÄÄÇ»ÅÍ¸À', 38500, NULL );
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G003', 'µÈÀå¸À ÃòÆÄ®½º', 5000, '±Ùµ¥ »öÀº °íÃßÀå»ö');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G004', '¼øÇÑ¸À ÇÏÇö¼ö', 999999, 'Á¨Æ²¹öÀü');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G005', '´ë¸Ó¸®¿ë °¡¹ß', 3200, '¸Ó¸Ó¸®¤»_¤»');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G006', '¾óÅ« °¨ÀÚÅÁ', 300, '°¨ÀÚÅÁ¸Ô°í½Í´Ù');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G007', 'ÈÆÂ¯ÀÇ ¿£ÅÍÅ°', 500000, '¿£ÅÍ»§');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G008', '¶ß°Å¿î ¾ÆÀÌ½º¾Æ¸Þ¸®Ä«³ë', 1150, '¤»¤±¤»');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G009', '¿©¸§¿ë ÄðÆÐµù', 110, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G010', '¹°Åë', 1250, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G011', 'BLAH BLAH', 1150, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G012', '¹ÝÆÈÆ¼', 1150, '³Ê¹«´õ¿ý');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G013', 'Ä¡Å²¸À ´Ü¹éÁú ½¦ÀÌÅ©', 9800, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G014', 'À±¼ø¿õÀÇ ÀÌÅ¬¸³½º', 2500, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G015', 'Á¶´ÜÀÇ ¿¹ÀýÁÖÀÔ ºüµû', 3800, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G016', '¾Æ Áý°¡°í½Í´Ù', 8282, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G017', 'ÀÌ°É ¿Ö ³Ö°í ÀÖÁö', 0000, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G018', 'COVID-19', 0000, NULL);
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G019', 'Ãß¼®¿¡ ¹ÞÀº »õ¹îµ· 2¸¸¿ø', 20000, 'ÀÔ±Ý¿Ï·á');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G020', '¼ÒÀ±ÀÇ È²±Ý¿Ã¸®ºê', 19200, '1ÀÏ1È²¿ÃSSAP°¡´É');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G021', 'Ä¿ÇÇ¸À ½º¸¶Æ®Æù',900000, '¾ÆÀÌÆùÀÓ');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G022', '°íÃß¹Ù»ç»è', 1150, '¹º°¡ ¹Ù»ç»è ÇØÁö´Â ¸À');
INSERT INTO GO(GO_CODE, GO_NAME, GO_PRICE, GO_COMMENTS)
VALUES ('G023', 'Á¾¿øÀÇ ¾÷½Å¿©±è', 1150, '²Ï³ª ±òº¸´Â ´«ºû');

INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G001', DEFAULT, 134, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G002', DEFAULT, 111, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G003', DEFAULT, 150, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G004', DEFAULT, 1, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G005', DEFAULT, 115, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G006', DEFAULT, 10, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G007', DEFAULT, 999, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G008', DEFAULT, 110, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G009', DEFAULT, 20, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G010', DEFAULT, 300, 20201231);
INSERT INTO SC(SC_GOCODE, SC_CODE, SC_STOCKS, SC_EXPIRE)
VALUES ('G011', DEFAULT, 100, 20201231);

SELECT * FROM GO;
SELECT * FROM SC;

--TEAM_SAM_SON
ALTER TABLE SAM.ORDERS
MODIFY OD_CODE DEFAULT SYSDATE;

 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E101', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E101', 'CM003', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E102', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E101', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E201', 'CM005', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E301', 'CM006', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E403', 'CM005', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES (DEFAULT, 'S004', 'E402', 'CM004', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E302', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E201', 'CM003', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E402', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E203', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E104', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E404', 'CM007', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E202', 'CM008', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E401', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S001', 'E104', 'CM001', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S004', 'E404', 'CM002', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E302', 'CM006', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S003', 'E301', 'CM005', 'P');
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(ADD_MONTHS(SYSDATE, -1), 'S003', 'E301', 'CM005', 'P');

 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160929', 'YYYYMMDDHH24MISS'), 'G001', '9', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160929', 'YYYYMMDDHH24MISS'), 'G005', '20', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160929', 'YYYYMMDDHH24MISS'), 'G002', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160932', 'YYYYMMDDHH24MISS'), 'G003', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160932', 'YYYYMMDDHH24MISS'), 'G004', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160932', 'YYYYMMDDHH24MISS'), 'G001', '0', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160934', 'YYYYMMDDHH24MISS'), 'G017', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160934', 'YYYYMMDDHH24MISS'), 'G016', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160934', 'YYYYMMDDHH24MISS'), 'G015', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160935', 'YYYYMMDDHH24MISS'), 'G004', '6', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160935', 'YYYYMMDDHH24MISS'), 'G007', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160935', 'YYYYMMDDHH24MISS'), 'G003', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160937', 'YYYYMMDDHH24MISS'), 'G008', '10', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160937', 'YYYYMMDDHH24MISS'), 'G011', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160937', 'YYYYMMDDHH24MISS'), 'G012', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160939', 'YYYYMMDDHH24MISS'), 'G006', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160939', 'YYYYMMDDHH24MISS'), 'G005', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160939', 'YYYYMMDDHH24MISS'), 'G004', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160941', 'YYYYMMDDHH24MISS'), 'G003', '10', 'P'); 
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160941', 'YYYYMMDDHH24MISS'), 'G015', '7', 'P'); 
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160941', 'YYYYMMDDHH24MISS'), 'G014', '3', 'P'); 
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160943', 'YYYYMMDDHH24MISS'), 'G001', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160943', 'YYYYMMDDHH24MISS'), 'G008', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160943', 'YYYYMMDDHH24MISS'), 'G009', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160944', 'YYYYMMDDHH24MISS'), 'G005', '20', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160944', 'YYYYMMDDHH24MISS'), 'G013', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160944', 'YYYYMMDDHH24MISS'), 'G014', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160946', 'YYYYMMDDHH24MISS'), 'G007', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160946', 'YYYYMMDDHH24MISS'), 'G016', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160946', 'YYYYMMDDHH24MISS'), 'G013', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160948', 'YYYYMMDDHH24MISS'), 'G012', '10', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160948', 'YYYYMMDDHH24MISS'), 'G001', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160948', 'YYYYMMDDHH24MISS'), 'G002', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160950', 'YYYYMMDDHH24MISS'), 'G015', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160950', 'YYYYMMDDHH24MISS'), 'G014', '12', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160950', 'YYYYMMDDHH24MISS'), 'G017', '10', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160951', 'YYYYMMDDHH24MISS'), 'G012', '13', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160951', 'YYYYMMDDHH24MISS'), 'G005', '40', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160951', 'YYYYMMDDHH24MISS'), 'G003', '50', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160953', 'YYYYMMDDHH24MISS'), 'G006', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160953', 'YYYYMMDDHH24MISS'), 'G008', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160953', 'YYYYMMDDHH24MISS'), 'G003', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160955', 'YYYYMMDDHH24MISS'), 'G013', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160955', 'YYYYMMDDHH24MISS'), 'G014', '8', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160955', 'YYYYMMDDHH24MISS'), 'G006', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160956', 'YYYYMMDDHH24MISS'), 'G005', '11', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160956', 'YYYYMMDDHH24MISS'), 'G003', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160956', 'YYYYMMDDHH24MISS'), 'G007', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160958', 'YYYYMMDDHH24MISS'), 'G003', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160958', 'YYYYMMDDHH24MISS'), 'G007', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160958', 'YYYYMMDDHH24MISS'), 'G002', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160959', 'YYYYMMDDHH24MISS'), 'G005', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160959', 'YYYYMMDDHH24MISS'), 'G009', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021160959', 'YYYYMMDDHH24MISS'), 'G016', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161001', 'YYYYMMDDHH24MISS'), 'G008', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161001', 'YYYYMMDDHH24MISS'), 'G003', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161001', 'YYYYMMDDHH24MISS'), 'G002', '5', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161002', 'YYYYMMDDHH24MISS'), 'G017', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161002', 'YYYYMMDDHH24MISS'), 'G012', '8', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20201021161002', 'YYYYMMDDHH24MISS'), 'G010', '4', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20200926145131', 'YYYYMMDDHH24MISS'), 'G005', '3', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20200926145131', 'YYYYMMDDHH24MISS'), 'G007', '1', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20200926145131', 'YYYYMMDDHH24MISS'), 'G008', '2', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20200926160239', 'YYYYMMDDHH24MISS'), 'G015', '7', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20200926145131', 'YYYYMMDDHH24MISS'), 'G014', '6', 'P');
 INSERT INTO OT(OT_ODCODE, OT_GOCODE, OT_QTY, OT_STATE)
 VALUES(TO_DATE('20200926160251', 'YYYYMMDDHH24MISS'), 'G008', '6', 'P');
 
 INSERT INTO OD(OD_CODE, OD_EMSTCODE, OD_EMCODE, OD_CMCODE, OD_STATE)
 VALUES(DEFAULT, 'S002', 'E202', 'CM007', 'P');
 DELETE FROM OD WHERE OD_CODE = '20201022100451';
/* 2020-10-22
    DML :: UPDATE ~ SET 
    SYNTAX__________
    UPDATE [TAB_NAME] SET [COL_NAME] = [VALUE];
    UPDATE [TAB_NAME] SET [COL_NAME] = [VALUE] WHERE [COL_NAME] [COMPARE] [VALUE] ;
*/
/* DELETE 
    SYNTAX___________
    DELETE FROM [TAB_NAME];
    DELETE FROM [TAB_NAME] WHERE [COL_NAME] [COMPARE] [VALUE];
*/
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160929';
 UPDATE OD SET OD_CODE =SYSDATE -3 WHERE OD_CODE ='20201021160929';
 UPDATE OT SET OT_ODCODE = '20201019101600' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160932';
 UPDATE OD SET OD_CODE =SYSDATE -3 WHERE OD_CODE ='20201021160934';
 UPDATE OT SET OT_ODCODE = '20201017102249' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160934';
 UPDATE OD SET OD_CODE =SYSDATE -5 WHERE OD_CODE ='20201021160932';
 UPDATE OT SET OT_ODCODE = '20201019102841' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160935';
 UPDATE OD SET OD_CODE =SYSDATE -5 WHERE OD_CODE ='20201021160935';
 UPDATE OT SET OT_ODCODE = '20201017103234' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160937';
 UPDATE OD SET OD_CODE =SYSDATE -7 WHERE OD_CODE ='20201021160937'; 
 UPDATE OT SET OT_ODCODE = '20201015103905' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160939';
 UPDATE OD SET OD_CODE =SYSDATE -7 WHERE OD_CODE ='20201021160939';
 UPDATE OT SET OT_ODCODE = '20201015104446' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160941';
 UPDATE OD SET OD_CODE =SYSDATE -9 WHERE OD_CODE ='20201021160941';
 UPDATE OT SET OT_ODCODE = '20201013104819' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160943';
 UPDATE OD SET OD_CODE =SYSDATE -9 WHERE OD_CODE ='20201021160943';
 UPDATE OT SET OT_ODCODE = '20201013105210' WHERE OT_ODCODE = '20201022100451'; 
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160944';
 UPDATE OD SET OD_CODE =SYSDATE -11 WHERE OD_CODE ='20201021160944';
 UPDATE OT SET OT_ODCODE = '20201011105545' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160946';
 UPDATE OD SET OD_CODE =SYSDATE -11 WHERE OD_CODE ='20201021160946'; 
 UPDATE OT SET OT_ODCODE = '20201011105849' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160948';
 UPDATE OD SET OD_CODE =SYSDATE -13 WHERE OD_CODE = '20201021160948';
 UPDATE OT SET OT_ODCODE = '20201009110156' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160950';
 UPDATE OD SET OD_CODE =SYSDATE -13 WHERE OD_CODE = '20201021160950';
 UPDATE OT SET OT_ODCODE = '20201009110538' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160951';
 UPDATE OD SET OD_CODE =SYSDATE -15 WHERE OD_CODE = '20201021160951';
 UPDATE OT SET OT_ODCODE = '20201007112343' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160953';
 UPDATE OD SET OD_CODE =SYSDATE -15 WHERE OD_CODE = '20201021160953';
 UPDATE OT SET OT_ODCODE = '20201007112603' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160955';
 UPDATE OD SET OD_CODE =SYSDATE -17 WHERE OD_CODE = '20201021160955';
 UPDATE OT SET OT_ODCODE = '20201005112831' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160956';
 UPDATE OD SET OD_CODE =SYSDATE -17 WHERE OD_CODE = '20201021160956';
 UPDATE OT SET OT_ODCODE = '20201005113057' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160958';
 UPDATE OD SET OD_CODE =SYSDATE -19 WHERE OD_CODE = '20201021160958';
 UPDATE OT SET OT_ODCODE = '20201003113318' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021160959';
 UPDATE OD SET OD_CODE =SYSDATE -19 WHERE OD_CODE = '20201021160959';
 UPDATE OT SET OT_ODCODE = '20201003113513' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021161001';
 UPDATE OD SET OD_CODE =SYSDATE -21 WHERE OD_CODE = '20201021161001';
 UPDATE OT SET OT_ODCODE = '20201001113754' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_ODCODE = '20201022100451' WHERE OT_ODCODE = '20201021161002';
 UPDATE OD SET OD_CODE =SYSDATE -21 WHERE OD_CODE = '20201021161002';
 UPDATE OT SET OT_ODCODE = '20201001113949' WHERE OT_ODCODE = '20201022100451';
 
 UPDATE OT SET OT_QTY = '4' WHERE OT_GOCODE = 'G001' AND OT_ODCODE ='20201017102249';
 
 UPDATE OT SET OT_STATE = 'R' WHERE OT_ODCODE = '20201003113318';
 UPDATE OT SET OT_STATE = 'R' WHERE OT_ODCODE = '20201001113949' AND OT_GOCODE ='G012';
 UPDATE OT SET OT_STATE = 'R' WHERE OT_ODCODE = '20201005113057' AND OT_GOCODE ='G007';
 UPDATE OT SET OT_STATE = 'R' WHERE OT_ODCODE = '20201005113057' AND OT_GOCODE ='G003';
 
 SELECT * FROM OD;
 SELECT * FROM OT;
 
 --TEAM_SAM_IU
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM001','±èÈÆ','01010001000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM002','ÀÓÈÆ','01020002000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM003','³²ÈÆ','01030003000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM004','ÀÌÈÆ','01040004000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM005','ÈÆÈÆ','01050005000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM006','ÃÖÈÆ','01060006000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM007','¹ÚÈÆ','01070007000');
INSERT INTO CM(CM_CODE, CM_NAME, CM_PHONE)
VALUES('CM008','¹éÈÆ','01080008000');

INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM001', TO_DATE('20201021160929','YYYYMMDDHH24MISS'), 1, '1000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM002', TO_DATE('20201021160932','YYYYMMDDHH24MISS'), -1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM003', TO_DATE('20201021160934','YYYYMMDDHH24MISS'), 1, '3000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20201021160935','YYYYMMDDHH24MISS'), -1, '4000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM005', TO_DATE('20201021160937','YYYYMMDDHH24MISS'), 1, '5000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM006', TO_DATE('20201021160939','YYYYMMDDHH24MISS'), -1, '6000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM007', TO_DATE('20201021160941','YYYYMMDDHH24MISS'), 1, '7000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM008', TO_DATE('20201021160943','YYYYMMDDHH24MISS'), -1, '8000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM001', TO_DATE('20201021160944','YYYYMMDDHH24MISS'), 1, '1000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM002', TO_DATE('20201021160946','YYYYMMDDHH24MISS'), -1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM003', TO_DATE('20201021160948','YYYYMMDDHH24MISS'), 1, '3000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20201021160950','YYYYMMDDHH24MISS'), -1, '4000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM005', TO_DATE('20201021160951','YYYYMMDDHH24MISS'), 1, '5000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM006', TO_DATE('20201021160953','YYYYMMDDHH24MISS'), -1, '6000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM007', TO_DATE('20201021160955','YYYYMMDDHH24MISS'), 1, '7000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM008', TO_DATE('20201021160956','YYYYMMDDHH24MISS'), -1, '8000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM001', TO_DATE('20201021160958','YYYYMMDDHH24MISS'), 1, '1000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM002', TO_DATE('20201021160959','YYYYMMDDHH24MISS'), -1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM003', TO_DATE('20201021161001','YYYYMMDDHH24MISS'), 1, '3000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20201021161002','YYYYMMDDHH24MISS'), -1, '4000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20200926145131','YYYYMMDDHH24MISS'), 1, '8000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20200926160239','YYYYMMDDHH24MISS'), 1, '2000');
INSERT INTO PO(PO_CMCODE, PO_ODCODE, PO_STATE, PO_AMOUNT)
VALUES('CM004', TO_DATE('20200926160251','YYYYMMDDHH24MISS'), -1, '1000');

/* 2020-10-22
    DML :: UPDATE ~ SET 
    SYNTAX__________
    UPDATE [TAB_NAME] SET [COL_NAME] = [VALUE];
    UPDATE [TAB_NAME] SET [COL_NAME] = [VALUE] WHERE [COL_NAME] [COMPARE] [VALUE] ;
*/
UPDATE PO SET PO_AMOUNT = 1000;
ROLLBACK;

UPDATE PO SET PO_AMOUNT = 10000 WHERE PO_CMCODE = 'CM008';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160929';
UPDATE PO SET PO_ODCODE = '20201019101600' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160932';
UPDATE PO SET PO_ODCODE = '20201017102249' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160934';
UPDATE PO SET PO_ODCODE = '20201019102841' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160935';
UPDATE PO SET PO_ODCODE = '20201017103234' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160937';
UPDATE PO SET PO_ODCODE = '20201015103905' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160939';
UPDATE PO SET PO_ODCODE = '20201015104446' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160941';
UPDATE PO SET PO_ODCODE = '20201013104819' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160943';
UPDATE PO SET PO_ODCODE = '20201013105210' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160944';
UPDATE PO SET PO_ODCODE = '20201011105545' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160946';
UPDATE PO SET PO_ODCODE = '20201011105849' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160948';
UPDATE PO SET PO_ODCODE = '20201009110156' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160950';
UPDATE PO SET PO_ODCODE = '20201009110538' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160951';
UPDATE PO SET PO_ODCODE = '20201007112343' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160953';
UPDATE PO SET PO_ODCODE = '20201007112603' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160955';
UPDATE PO SET PO_ODCODE = '20201005112831' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160956';
UPDATE PO SET PO_ODCODE = '20201005113057' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160958';
UPDATE PO SET PO_ODCODE = '20201003113318' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021160959';
UPDATE PO SET PO_ODCODE = '20201003113513' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021161001';
UPDATE PO SET PO_ODCODE = '20201001113754' WHERE PO_ODCODE = '20201022100451';

UPDATE PO SET PO_ODCODE = '20201022100451' WHERE PO_ODCODE = '20201021161002';
UPDATE PO SET PO_ODCODE = '20201001113949' WHERE PO_ODCODE = '20201022100451';

SELECT * FROM CM;
SELECT * FROM PO;


