SELECT * FROM DBA_USERS;

DROP USER RE CASCADE;
DROP USER RAM CASCADE;
DROP USER ZERO CASCADE;
DROP USER UKJW CASCADE;
DROP USER KJW CASCADE;

CREATE USER SAM
IDENTIFIED BY "0000";

GRANT DBA TO SAM;

INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S001', 'SAM_MART_J', 'ÀÍ»ê½Ã ¿µµîµ¿');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S002', 'SAM_MART_H', 'ÀÎÃµ±¤¿ª½Ã ºÎÆò±¸');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S003', 'SAM_MART_Y', 'ÀÎÃµ±¤¿ª½Ã ¹ÌÃßÈ¦±¸');
INSERT INTO ST(ST_CODE, ST_NAME, ST_ADDR)
VALUES('S004', 'SAM_MART_M', 'ÀÎÃµ±¤¿ª½Ã ³²µ¿±¸');

INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E101', '1111', '±èÁ¾¿ø', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E102', '1111', 'ÇÏÇö¼ö', 'A' );
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E103', '1111', 'À¯¿µ¹Î', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S001', 'E104', '1111', '±è¹Î±â', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E201', '2222', '±èÁ¾¿ø', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E202', '2222', 'ÇÏÇö¼ö', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E203', '2222', 'À¯¿µ¹Î', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S002', 'E204', '2222', '±è¹Î±â', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E301', '3333', '±èÁ¾¿ø', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E302', '3333', 'ÇÏÇö¼ö', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E303', '3333', 'À¯¿µ¹Î', 'M');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S003', 'E304', '3333', '±è¹Î±â', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E401', '4444', '±èÁ¾¿ø', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E402', '4444', 'ÇÏÇö¼ö', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E403', '4444', 'À¯¿µ¹Î', 'A');
INSERT INTO "EM"(EM_STCODE, EM_CODE, EM_PWD, EM_NAME, EM_LEVEL)
VALUES('S004', 'E404', '4444', '±è¹Î±â', 'M');

SELECT EM_STCODE AS "STCODE",
    EM_CODE AS "EMCODE",
    EM_NAME AS "EMNAME",
    EM_LEVEL AS "EMLEVEL"
FROM "EM"
WHERE EM_STCODE = 'S001' AND EM_CODE = 'E102';

SELECT GO_CODE AS "GOCODE",
    GO_NAME AS "GONAME",
    GO_PRICE AS "GOPRICE",
    GO_COMMENTS AS "GOCOMMENTS"
FROM GO;

SELECT GO_CODE AS "GOCODE",
    GO_NAME AS "GONAME",
    GO_PRICE AS "GOPRICE",
    GO_COMMENTS AS "GOCOMMENTS"
FROM GO
WHERE GO_CODE = 'G008' OR GO_CODE = 'G005' OR GO_CODE = 'G022';

SELECT GO_CODE AS "GOCODE",
    GO_NAME AS "GONAME",
    GO_PRICE AS "GOPRICE",
    GO_COMMENTS AS "GOCOMMENTS"
FROM GO
WHERE GO_CODE IN(SELECT OT_GOCODE
                FROM OT);

SELECT *
FROM OT
WHERE OT_ODCODE LIKE '20201013' || '%';

SELECT ABS(65), ABS(-65)
FROM DUAL;

SELECT CEIL(1.956), FLOOR(1.956)
FROM DUAL;

SELECT 7/2, MOD(7, 2)
FROM DUAL;

SELECT ROUND(21.637, 0), ROUND(21.637, 1), ROUND(21.637, -1)
FROM DUAL;

SELECT ROUND(21.637, 0), TRUNC(21.637, 0)
FROM DUAL;

SELECT CONCAT(CONCAT('TEAM', 'SAM'), 'FANA'), 'TEAM' || 'SAM' || 'FANA'
FROM DUAL;

SELECT INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1),
    INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1, 2),
    INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1, 3),
    INSTR('TEADFSLIELSFDLKFJTEADISKETEA', 'TEA', 1, 4)
FROM DUAL;

SELECT TO_CHAR('1000000000000', 'L9,999,999,999,990'),
    TO_CHAR('0', 'L9,999,999,999,900'),
    TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    TO_DATE('201023095700', 'YYMMDDHH24MISS')
FROM DUAL;

SELECT SYSDATE AS "¿À´Ã",
    SYSDATE + 3 AS "3ÀÏ µÚ",
    ADD_MONTHS(SYSDATE, 3) AS "3°³¿ù µÚ",
    MONTHS_BETWEEN(SYSDATE, ADD_MONTHS(SYSDATE, 3)) AS "¿À´Ã - 3°³¿ù µÚ",
    MONTHS_BETWEEN(ADD_MONTHS(SYSDATE, 3), SYSDATE) AS "3°³¿ù µÚ - ¿À´Ã",
    LAST_DAY(ADD_MONTHS(SYSDATE, 3)) AS "3°³¿ù µÚ ¸¶Áö¸· ³¯",
    NEXT_DAY(ADD_MONTHS(SYSDATE, 3), 7) AS "3°³¿ù µÚ ÀÏ¿äÀÏ"
FROM DUAL;

SELECT GO.GO_CODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    GO.GO_PRICE AS "GOPRICE",
    SC.SC_EXPIRE AS "SCEXPIRE"
FROM GO INNER JOIN SC ON GO.GO_CODE = SC.SC_GOCODE;

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R' AND OT.OT_ODCODE = '20201003113318';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R' AND OT.OT_GOCODE = 'G003';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE = 'R' AND (OT.OT_GOCODE = 'G003' OR OT.OT_GOCODE = 'G007');

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R' AND OT.OT_ODCODE = '20201003113318';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R' AND OT.OT_GOCODE = 'G003';

SELECT OT.OT_ODCODE AS "ODCODE",
    OT.OT_GOCODE AS "GOCODE",
    GO.GO_NAME AS "GONAME",
    OT.OT_QTY AS "OTQTY",
    GO.GO_PRICE AS "GOPRICE",
    OT.OT_QTY*GO.GO_PRICE AS "PRICE"
FROM OT INNER JOIN GO ON OT.OT_GOCODE = GO.GO_CODE
WHERE OT.OT_STATE != 'R' AND (OT.OT_GOCODE = 'G003' OR OT.OT_GOCODE = 'G007');

SELECT STNAME,
    EMNAME,
    EMLEVEL
FROM SAM.EMPLOYEEINFO
WHERE STCODE = 'S001';

SELECT STNAME,
    EMNAME,
    EMLEVEL
FROM SAM.EMPLOYEEINFO
WHERE EMCODE = 'E101';

SELECT STNAME,
    EMNAME,
    ODCODE,
    GONAME,
    OTQTY,
    GOPRICE,
    PRICE
FROM SAM.ORDERINFO
WHERE EMCODE = 'E101' AND ODCODE >= (ADD_MONTHS(SYSDATE, -1));

SELECT ODCODE,
    GONAME,
    OTQTY,
    GOPRICE,
    PRICE
FROM SAM.ORDERINFO
WHERE GOCODE = 'G005' AND ODCODE >= (ADD_MONTHS(SYSDATE, -1));

SELECT *
FROM SAM.ORDERINFO
WHERE OTSTATE != 'R' AND (GOCODE = 'G003' OR GOCODE = 'G007');

COMMIT;

SELECT * FROM "EM";
SELECT * FROM USER_TAB_PRIVS_RECD;

